version: '3.8'

services:
  prompt-manager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3501:3501"
    volumes:
      - prompt-data:/app/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  prompt-data: